sudo: required
services:
  - docker

before_install:
  - docker build -t johpie/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run johpie/react-test npm test -- --coverage

after_success:
  - docker build -t johpie/multi-client -f ./client
  - docker build -t johpie/multi-nginx -f ./nginx
  - docker build -t johpie/multi-server -f ./server
  - docker build -t johpie/multi-worker -f ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push johpie/multi-client
  - docker push johpie/mutli-nginx
  - docker push johpie/multi-server
  - docker push johpie/multi-worker
